# Generated by Django 5.0.2 on 2024-02-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='books_posted',
            field=models.IntegerField(default=0),
        ),
    ]
