# Generated by Django 5.0.2 on 2024-02-27 00:45

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userprofile_profile_picture_book_cart_cartitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='books_posted',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(upload_to=api.models.BookCoverImagePathGenerator()),
        ),
        migrations.AlterField(
            model_name='book',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_posted', to=settings.AUTH_USER_MODEL),
        ),
    ]
