# Generated by Django 5.0.2 on 2024-03-03 04:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_message_notification_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to=api.models.ProfileImagePathGenerator()),
        ),
    ]
