POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{
    "username": "wisdom1",
    "password": "Good!@#$%^&*Pass123"
}

###
POST http://127.0.0.1:8000/api/register
Content-Type: application/json

{"username": "wisdom1", "password": "Good!@#$%^&*Pass123", "password2": "Good!@#$%^&*Pass123","email": "wisdom1@gmail.com", "first_name": "wisdom", "last_name": "castro"
}

###
GET http://127.0.0.1:8000/api/profile
Content-Type: application/json
Authorization: Token 4aea093b57c8469c108528332e4b2413b7bd636c
###

POST http://127.0.0.1:8000/api/logout
Content-Type: application/json
Authorization : Token 4aea093b57c8469c108528332e4b2413b7bd636c

###
PUT http://127.0.0.1:8000/api/profile/edit
Content-Type: application/json
Authorization: Token 2cbc8c56f652956f110354032988f19eaf9a3af0
    
    {"username": "wisdom1", "email": "isaacokechukwu22@gmail.com"}
###